# ============================================================
# SkillHub Backend - Configuration SonarCloud
# ============================================================

sonar.projectKey=poun-2108_skillhub-back_CICD
sonar.projectName=skillhub-back_CICD
sonar.projectVersion=1.0
sonar.organization=poun-2108

sonar.sources=app
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.php.coverage.reportPaths=build/logs/clover.xml
sonar.php.tests.reportPath=build/logs/junit.xml

sonar.exclusions=vendor/**,node_modules/**,database/**,storage/**,bootstrap/**,public/**,resources/**

sonar.coverage.exclusions=app/Http/Middleware/**,app/Providers/**,app/Mail/**,app/Console/**

sonar.cpd.exclusions=app/Http/Middleware/**,app/Providers/**

sonar.coverage.exclusions=app/Http/Controllers/MessageController.php,app/Models/Message.php,app/Models/FormationVue.php
